[build]
  command = "composer install --no-dev && php artisan config:clear"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.0"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
